export default {
    white: "white",
    black: "black",
    grey: "grey",
    lightgrey: "lightgrey",
    darkgrey: "darkgrey",
    primary: "royalblue",
    secondary: "mediumseagreen",
    green: "green",
    lightgreen: "lightgreen",
    red:"red",
    darkred: "darkred",
    lightred: "indianred",
    gold: "goldenrod",
    lightprimary: "lightsteelblue",
    indigo: "indigo",
}