export default Object.freeze({
    CREATE_ROUTINE: 'CreateRoutine',
    CREATE_WORKOUT: 'CreateWorkout',
    LISTING_USERS: 'ListingUsers',
    LISTING_ROUTINES: 'ListingRoutines',
    LISTING_WORKOUTS: 'ListingWorkouts',
    LISTING_ASSOCIATIONS: 'ListingAssociations',
    MY_ACCOUNT: "Yo",
    MY_DETAILS: 'MyDetails',
    PRESCRIBE_TO_USER: "PrescribeToUser",
    PRESCRIPTION_TYPES: "PrescriptionTypes",
    PRESCRIPTION_DETAILS: "PrescriptionDetails",
    ASSOCIATE: "Associate",
    ASSOCIATION_DETAILS: "AssociationDetails",
    ROUTINE_DETAILS: 'RoutineDetails',
    USER_DETAILS: 'UserDetails',
    USER_PRESCRIPTIONS: "ListingUserPrescriptions",
    WORKOUT_DETAILS: 'WorkoutDetails',
    WELCOME: 'Welcome',

})