export default Object.freeze({
    ABOUT: "About",
    ASSOCIATE: "Associate",
    CREATE_ROUTINE: 'CreateRoutine',
    CREATE_WORKOUT: 'CreateWorkout',
    DO_WORKOUT: "DoingWorkout",
    LISTING_USERS: 'ListingUsers',
    LISTING_ROUTINES: 'ListingRoutines',
    LISTING_WORKOUTS: 'ListingWorkouts',
    MY_ACCOUNT: "Yo",
    MY_DETAILS: 'MyDetails',
    PRESCRIBE_TO_USER: "PrescribeToUser",
    PRESCRIPTION_DETAILS: "PrescriptionDetails",
    PRESCRIPTION_TYPES: "PrescriptionTypes",
    ROUTINE_DETAILS: 'RoutineDetails',
    USER_DETAILS: 'UserDetails',
    USER_PRESCRIPTIONS: "ListingUserPrescriptions",
    USER_RECORDS: "ListingRecords",
    WATCH_LIVE: 'WatchingLive',
    WELCOME: 'Welcome',
    WORKOUT_DETAILS: 'WorkoutDetails',
});